### ISSUE TITLE
Refactor LoginHandler.ServeHTTP(w http.ResponseWriter, r *http.Request)

### ISSUE THREAD

**Issue by MichielCuijpersHackatonSupport** [BeyondBankingDays/minions-api#1]
I've selected [**LoginHandler.ServeHTTP(w http.ResponseWriter, r *http.Request)**](https://github.com/BeyondBankingDays/minions-api/blob/4ea4d5fc28d61f3f24a6e49d869ec9ab894915ab/api/user.go#L149-L182) for refactoring, which is a unit of **29** lines of code. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Short Units of Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the length of code units to 15 lines of code.
- **Why**❓ 
Small units are easier to analyse, test and reuse.
- **How** 🔧 
When writing new units, don't let them grow above 15 lines of code. When a unit grows beyond this, split it in smaller units of no longer than 15 lines.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by MichielCuijpersHackatonSupport** [comment]
if you would refactor this candidate you will gain a full guideline
<img width="1121" alt="schermafbeelding 2018-06-09 om 22 14 56" src="https://user-images.githubusercontent.com/40090841/41195675-97d24c5c-6c32-11e8-98e9-2045b8bd8a3d.png">

**Comment by mvmaasakkers** [comment]
Done! Thanks!
